### ISSUE TITLE
xlabel units in derivative plot of apShape.py

### ISSUE THREAD

**Issue by saglag** [swharden/pyABFauto#7]
xlabel units currently labelled as "ms" when voltage is plotted on the axis on line 57 of apShape.py

**Comment by swharden** [comment]
FYI, GitHub allows linking to lines in source code like this:

https://github.com/swharden/pyABFauto/blob/2a6c38f9b504548c120ffb991e9b4c3b3d255caf/src/pyABFauto/analyses/apShape.py#L43

https://github.com/swharden/pyABFauto/blob/2a6c38f9b504548c120ffb991e9b4c3b3d255caf/src/pyABFauto/analyses/apShape.py#L57

Thanks for the tip! I corrected these lines with 565b739
